SEMAGLUTIDE:
  names:
  - SEMAGLUTIDE
  - OZEMPIC
  - RYBELSUS
  - WEGOVY
  comparators:
  - - DULAGLUTIDE
    - TRULICITY
  - - LIRAGLUTIDE
    - SAXENDA
    - XULTOPHY
    - VICTOZA
  - - EXENATIDE
    - BYDUREON
    - BYETTA
ROFECOXIB:
  names:
  - ROFECOXIB
  comparators:
  - - CELECOXIB
    - CONSENSI
    - CELEBREX
    - ELYXYB
  - - VALDECOXIB
  - - ETORICOXIB
LIRAGLUTIDE:
  names:
  - LIRAGLUTIDE
  - SAXENDA
  - XULTOPHY
  - VICTOZA
  comparators:
  - - INSULIN DETEMIR
    - LEVEMIR
  - - INSULIN DEGLUDEC
    - TRESIBA
    - XULTOPHY
  - - INSULIN, REGULAR, HUMAN
    - NOVOLIN
    - HUMULIN
    - AFREZZA
  - - INSULIN GLARGINE
    - TOUJEO
    - BASAGLAR
    - SOLIQUA
